application: ztahomework
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /(.*\.(jpg|png|ico))
  static_files: static/images/\1
  upload: static/images/(.*\.(jpg|png|ico))

- url: /(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /.*
  script: main.py